stages:
  - test

image: node:latest

test:
  stage: test
  services:
    - postgres:latest
  variables:
    POSTGRES_DB: postgres
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: ""
    POSTGRES_TEST_URL: postgres://postgres@postgres:5432/postgres
  script:
    - npm i -g yarn
    - yarn install
    - yarn test
