version: '3.3'

services:
  db_dev:
    image: postgres:latest
    restart: always
    ports:
      - 9000:5432

  app_dev:
    restart: always
    build: .
    volumes:
      - .:/app
    command: yarn dev
    ports:
      - '3100:3100'
    links:
      - db_dev
    environment:
      POSTGRES_URL: postgres://postgres@db_dev:9000/postgres
