version: '3'

services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432

  app:
    build: .
    command: bash -c "yarn && yarn dev"
    volumes:
      - .:/home
    ports:
      - 3000:3000
    links:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres@postgres/postgres
