version: '3.3'

services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432

  postgres_test:
    image: postgres:latest
    restart: always
    ports:
      - 5431:5432
