# https://discuss.circleci.com/t/setting-up-postgres-with-circleci-for-node/14657/3
version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: node:current
        environment:
          NODE_ENV: test
          POSTGRES_URL: postgres://postgres@localhost:5432/postgres
      - image: postgres:latest
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - repo-yarn-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - repo-yarn-
      - run: yarn install
      - save_cache:
          paths:
            - ~/.yarn-cache
          key: repo-yarn-{{ checksum "yarn.lock" }}
      # Wait for Postgres connection to open.
      # - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      # Run validation checks & generate coverage reports
      - run: yarn test
