version: 2

jobs:
  build:
    docker:
      - image: node:current
        environment:
          POSTGRES_TEST_URL: postgres://postgres@localhost:5432/postgres
      - image: postgres:latest
    steps:
      - checkout
      - run: yarn install
      - run: yarn test
      - store_test_results:
          path: coverage/lcov-report
      - store_artifacts:
          path: coverage/lcov-report
